"""empty message

Revision ID: 2693870e9f5c4d4c9f6096468847bf9e
Revises:
Create Date: 2024-01-28 20:59:01.324180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2693870e9f5c4d4c9f6096468847bf9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abcd',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('second_name', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
