name: SonarCloud analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Poetry install
        run: pip install poetry poethepoet
      - name: Install poetry dependencies
        run: poetry install --with=test
      - name: Run tests
        run: poetry poe test_postgres
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          args:
            -Dsonar.projectKey=adamhmetal_redbeanpython
            -Dsonar.organization=adamhmetal1
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.version=3.11
            -Dsonar.sources=./redbeanpython
            -Dsonar.tests=./tests
            -Dsonar.projectBaseDir=.
            -Dsonar.dynamicAnalysis=reuseReports
            -Dsonar.sonar.scm.provider=git
            -Dsonar.python.coverage.reportPaths=./tests/coverage.xml

